/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoestudio.gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;

/**
 *
 * @author Vitor0liveira
 */
public class JFrameCliente extends JFrame {

    /**
     * Creates new form JFrameCliente
     */
    private void menuItem4ActionPerformed(ActionEvent e) {
        // TODO add your code here    
        JInternalFrameCliente cadCli = new JInternalFrameCliente();
        cadCli.setVisible(true);

    }

    private void menuItem3ActionPerformed(ActionEvent e) {
        // TODO add your code here
        JOptionPane.showMessageDialog(null, "Developer Vitor Oliveira.");
    }

    public JFrameCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Vitor Oliveira
    private void initComponents() {
        TelaMain = new JFrame();
        desktopPane = new JDesktopPane();
        menuBar1 = new JMenuBar();
        menu1 = new JMenu();
        menuItem3 = new JMenuItem();
        menuItem6 = new JMenuItem();
        menu2 = new JMenu();
        menuItem4 = new JMenuItem();
        menuItem5 = new JMenuItem();

        //======== TelaMain ========
        {
            TelaMain.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            TelaMain.setForeground(Color.white);
            TelaMain.setTitle("Main");
            Container TelaMainContentPane = TelaMain.getContentPane();

            //======== desktopPane ========
            {
                desktopPane.setBackground(Color.gray);

                //======== menuBar1 ========
                {

                    //======== menu1 ========
                    {
                        menu1.setText("Exit");

                        //---- menuItem3 ----
                        menuItem3.setText("Sobre");
                        menuItem3.addActionListener(e -> menuItem3ActionPerformed(e));
                        menu1.add(menuItem3);

                        //---- menuItem6 ----
                        menuItem6.setText("Vers\u00e3o");
                        menu1.add(menuItem6);
                    }
                    menuBar1.add(menu1);

                    //======== menu2 ========
                    {
                        menu2.setText("Cliente");

                        //---- menuItem4 ----
                        menuItem4.setText("Cadastrar");
                        menuItem4.addActionListener(e -> {
			menuItem4ActionPerformed(e);
			menuItem4ActionPerformed(e);
			menuItem4ActionPerformed(e);
		});
                        menu2.add(menuItem4);

                        //---- menuItem5 ----
                        menuItem5.setText("Pesquisar");
                        menu2.add(menuItem5);
                    }
                    menuBar1.add(menu2);
                }
                desktopPane.add(menuBar1, JLayeredPane.DEFAULT_LAYER);
                menuBar1.setBounds(0, 0, 410, menuBar1.getPreferredSize().height);
            }

            GroupLayout TelaMainContentPaneLayout = new GroupLayout(TelaMainContentPane);
            TelaMainContentPane.setLayout(TelaMainContentPaneLayout);
            TelaMainContentPaneLayout.setHorizontalGroup(
                TelaMainContentPaneLayout.createParallelGroup()
                    .addComponent(desktopPane, GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            );
            TelaMainContentPaneLayout.setVerticalGroup(
                TelaMainContentPaneLayout.createParallelGroup()
                    .addComponent(desktopPane, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            );
            TelaMain.pack();
            TelaMain.setLocationRelativeTo(null);
        }
    }
    // </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameCliente frame = new JFrameCliente();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Vitor Oliveira
    private JFrame TelaMain;
    private JDesktopPane desktopPane;
    private JMenuBar menuBar1;
    private JMenu menu1;
    private JMenuItem menuItem3;
    private JMenuItem menuItem6;
    private JMenu menu2;
    private JMenuItem menuItem4;
    private JMenuItem menuItem5;
    // End of variables declaration//GEN-END:variables

}
